// <auto-generated />
namespace IvanovBand.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddConcert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConcert));
        
        string IMigrationMetadata.Id
        {
            get { return "201503281723012_AddConcert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
